[project]
name = "oversight-curriculum"
version = "1.0.0"
description = "AI Safety & Reasoning System - Oversight Curriculum"
authors = [
    { name = "Oversight Curriculum Team", email = "team@example.com" }
]
readme = "README.md"
license = { text = "MIT" }
requires-python = ">=3.8"
keywords = ["ai-safety", "reasoning", "oversight", "curriculum", "claude", "anthropic", "machine-learning"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
dependencies = [
    "anthropic>=0.7.0",
    "matplotlib>=3.5.0",
    "numpy>=1.21.0",
    "pandas>=1.5.0",
    "seaborn>=0.12.0",
    "scikit-learn>=1.3.0",
    "scipy>=1.11.0",
    "tqdm>=4.65.0",
    "colorama>=0.4.6",
    "psutil>=5.9.0",
    "python-dotenv>=1.0.0",
    "requests>=2.31.0",
    "pydantic>=2.0.0",
    "PyYAML>=6.0",
    "httpx>=0.24.0",
    "tenacity>=8.2.0",
    "structlog>=23.0.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=7.4.0",
    "pytest-asyncio>=0.21.0",
    "pytest-cov>=4.1.0",
    "pytest-mock>=3.10.0",
    "hypothesis>=6.75.0",
    "black>=23.0.0",
    "ruff>=0.1.0",
    "flake8>=6.0.0",
    "mypy>=1.5.0",
    "isort>=5.12.0",
    "pre-commit>=3.3.0",
    "jupyter>=1.0.0",
    "ipykernel>=6.25.0",
    "coverage>=7.2.0",
]

[project.urls]
Homepage = "https://github.com/oversight-curriculum/oversight-curriculum"
Documentation = "https://github.com/oversight-curriculum/oversight-curriculum#readme"
Repository = "https://github.com/oversight-curriculum/oversight-curriculum"
Issues = "https://github.com/oversight-curriculum/oversight-curriculum/issues"
Changelog = "https://github.com/oversight-curriculum/oversight-curriculum/blob/main/CHANGELOG.md"

[project.scripts]
oversight = "oversight_curriculum.src.__main__:main"

[tool.setuptools]
packages = ["oversight_curriculum"]
include-package-data = true

[tool.setuptools.package-data]
# Include docs and results for diagrams and metrics
"oversight_curriculum" = ["docs/*", "results/*", "config/*"]

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta" 