[project]
name = "oversight"
version = "1.0.0"
description = "AI Safety & Reasoning System - Oversight Curriculum"
authors = [
    { name = "Oversight Curriculum Team", email = "team@example.com" }
]
readme = "README.md"
requires-python = ">=3.8"
dependencies = []

[tool.setuptools]
packages = ["oversight_curriculum"]
include-package-data = true

[tool.setuptools.package-data]
# Include docs and results for diagrams and metrics
"oversight_curriculum" = ["docs/*", "results/*", "config/*"] 