# Oversight Curriculum Configuration
# Central configuration file to replace all magic numbers and hard-coded values

# Model Configuration
model:
  name: "claude-3-5-sonnet-20241022"
  max_tokens: 512
  temperature: 0.7
  timeout_seconds: 30

# Execution Configuration
execution:
  # Demo mode settings
  demo:
    cycles: 2
    max_puzzles_per_cycle: 1
    max_solutions_per_puzzle: 1
    enable_referee: true
    enable_hhh_filter: false
    enable_best_of_n: false

  # Robust mode settings
  robust:
    cycles: 10
    max_puzzles_per_cycle: 3
    max_solutions_per_puzzle: 2
    enable_referee: true
    enable_hhh_filter: true
    enable_best_of_n: true

  # Hackathon mode settings
  hackathon:
    cycles: 5
    max_puzzles_per_cycle: 2
    max_solutions_per_puzzle: 1
    enable_referee: true
    enable_hhh_filter: true
    enable_best_of_n: false

# Safety Configuration
safety:
  enable_referee: true
  enable_hhh_filter: true
  enable_best_of_n: false
  strict_mode: false

  # Referee settings
  referee:
    safety_threshold: 0.7
    complexity_threshold: 0.3
    banned_keywords:
      - "hack"
      - "exploit"
      - "vulnerability"
      - "password"
      - "credit_card"
      - "delete"
      - "rm -rf"
      - "os.system"
      - "subprocess"

  # HHH filter settings
  hhh_filter:
    safety_level: "medium"  # low, medium, high
    max_harm_score: 0.5
    enable_strict_mode: false

# Best-of-N Configuration
best_of_n:
  enabled: false
  n_samples: 16
  selection_method: "reward"  # reward, safety, combined
  min_samples: 3

# Metrics Configuration
metrics:
  enable_csv_export: true
  enable_json_export: true
  enable_plots: true
  save_intermediate_results: true

  # Success criteria
  success_criteria:
    baseline_approval_rate: 0.6
    oversight_approval_rate: 0.7
    learning_improvement: 0.15
    safety_compliance: 0.05

# Output Configuration
output:
  base_dir: "results"
  create_timestamped_dirs: true
  save_logs: true
  save_plots: true
  save_reports: true

  # File naming
  file_patterns:
    baseline_metrics: "baseline_metrics_{timestamp}.json"
    oversight_metrics: "oversight_metrics_{timestamp}.json"
    comparison_results: "comparison_results_{timestamp}.json"
    summary_report: "summary_report_{timestamp}.txt"

# Cost Management
cost:
  max_usd_per_run: 15.0
  enable_monitoring: true
  alert_threshold: 10.0

  # API cost estimates (per 1K tokens)
  api_costs:
    claude-3-5-sonnet-20241022:
      input: 0.003
      output: 0.015

# Logging Configuration
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  enable_file_logging: true
  enable_console_logging: true

  # Log files
  files:
    main: "logs/oversight.log"
    errors: "logs/errors.log"
    metrics: "logs/metrics.log"

# Testing Configuration
testing:
  enable_mocks: true
  mock_api_responses: true
  test_timeout: 30
  enable_coverage: true
  coverage_threshold: 80

  # Test data
  test_puzzles:
    - id: "test_puzzle_1"
      type: "code_i"
      content: "def add(a, b): return a + b"
    - id: "test_puzzle_2"
      type: "code_o"
      content: "def multiply(x, y): return x * y"

# Development Configuration
development:
  enable_debug_mode: false
  enable_profiling: false
  enable_memory_tracking: false

  # Debug settings
  debug:
    log_api_calls: false
    log_metrics_details: false
    save_intermediate_states: false
