name: Security Scan

on:
  schedule:
    - cron: '0 0 * * 0'  # Weekly
  push:
    branches: [ main ]

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Run Bandit security scan
      uses: python-security/bandit-action@v1
      with:
        path: oversight/
        level: medium
        confidence: medium

    - name: Run Safety check
      run: |
        pip install safety
        safety check
