name: Validate Documentation

on:
  push:
    paths:
      - 'README.md'
      - 'MVP_DEMO.md'
      - 'validate_docs.py'
  pull_request:
    paths:
      - 'README.md'
      - 'MVP_DEMO.md'
      - 'validate_docs.py'

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Validate documentation
      run: |
        python validate_docs.py

    - name: Check demo script
      run: |
        chmod +x demo.sh
        echo "Demo script is executable"

    - name: Verify commands work
      run: |
        python -m oversight.features.humaneval_integration --help
        python -m oversight.features.red_team_suite --help
        echo "All commands work correctly"
